name: saropa_dart_utils
description: "Boilerplate reduction tools and human-readable extension methods by Saropa"
version: 1.0.2

homepage: https://app.saropa.com
repository: https://github.com/saropa/saropa_dart_utils
issue_tracker: https://github.com/saropa/saropa_dart_utils/issues
documentation: https://pub.dev/documentation/saropa_dart_utils/latest/

environment:
  sdk: ">=3.9.0 <4.0.0" # detect: flutter doctor -v Dart version
  flutter: ">=3.35.1" # run: flutter upgrade

dependencies:
  # Provides grapheme (user-perceived character) cluster support for Dart strings.
  # https://pub.dev/packages/characters/changelog
  characters: ^1.4.0

  # Contains utility functions and classes in the style of dart:collection to make working with collections easier.
  # https://pub.dev/packages/collection/changelog
  collection: ^1.19.1

  flutter:
    sdk: flutter

  # International date formats
  # https://pub.dev/packages/intl/changelog
  # NOTE: intl comes with a horrible mess of dependencies ... it would be great to resolve this once and for all
  # intl: ^0.20.2

  # Jiffy is a Flutter (Android, IOS and Web) date time package inspired by moment js for parsing, manipulating, querying and formatting dates
  # https://pub.dev/packages/jiffy/changelog
  jiffy: ^6.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # CLI tool for running custom lints
  # https://pub.dev/packages/custom_lint/changelog
  # NOTE: 0.8.1 - 2025-09-09 Support analyzer 8.0.0
  custom_lint: ^0.8.0

  # 1,000+ lint rules for Flutter and Dart. Free. Open source.
  # https://pub.dev/packages/saropa_lints/changelog
  saropa_lints: ^1.5.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
